src/WinnersLeague.Web/Controllers/LeaderBoardsController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Common;
    using WinnersLeague.Models;
    using WinnersLeague.Web.Models.UserModels;
    using WinnersLeague.Services.Mapping;
    using WinnersLeague.Services.Data.Contracts;

    public class LeaderboardsController : Controller
    {
        private readonly IRepository<WinnersLeagueUser> userRepository;
        private readonly IRepository<League> leagueRepository;
        private readonly IBetService betService;
        private readonly IMatchService matchService;

        public LeaderboardsController(IRepository<WinnersLeagueUser> userRepository,
            IRepository<League> leagueRepository,  IBetService betService
            , IMatchService matchService)
        {
            this.matchService = matchService;
            this.userRepository = userRepository;
            this.leagueRepository = leagueRepository;
            this.betService = betService;
        }

        public IActionResult UsersList()
        {
            var users = this.userRepository
                .All().To<UserViewModel>()
                .OrderByDescending(x => x.WinStats)
                .ThenByDescending(x => x.Points)
                .ToList();

            this.betService.CheckingIsWiningBetsAsync();
            

            return this.View(users);
        }

        public async Task<IActionResult> LeagueList(string name)
        {
            var league = this.leagueRepository
                .All()
                .FirstOrDefault(x => x.Name == name);

            await this.matchService.CheckingLeagueMatchesAsync();

            return this.View(league);
        }
    }
}

src/WinnersLeague.Web/Controllers/TeamsController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Services.Data.Contracts;


    public class TeamsController : Controller
    {
        private readonly ITeamService teamService;

        public TeamsController(ITeamService teamService)
        {
            this.teamService = teamService;
        }

        public IActionResult Details(string id)
        {
            var team = this.teamService
                .GetAll()
                .FirstOrDefault(x => x.Id == id);


            return this.View(team);
        } 

        public IActionResult All(string searchText)
        {
            searchText = searchText ?? "";
            searchText = searchText.Trim();

            var teams = this.teamService.GetAll()
                .Where(x => x.Name.ToLower()
                .Contains(searchText.ToLower()));

            return this.View(teams);
        }
    }
}

src/WinnersLeague.Web/Views/Leaderboards/LeagueList.cshtml
@model League

@{
    ViewData["Title"] = "LeagueList";
    var counter = 0;
}

<h2>Premier League</h2>

<table class="table table-hover table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Logo</th>
            <th scope="col">Name</th>
            <th scope="col">Wins</th>
            <th scope="col">Draws</th>
            <th scope="col">Loses</th>
            <th scope="col">Points</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var team in Model.Teams.OrderByDescending(x => x.Points).ToList())
        {
            counter++;
                <tr >
                    <th scope="row">@counter</th>
                    <td><img src="@Url.Content(team.Logo)" width="24" height="24" alt="Logo" /></td>
                    <td><a class="text-white" asp-controller="Teams" asp-action="Details" asp-route-id="@team.Id">@team.Name</a></td>
                    <td>@team.Wins</td>
                    <td>@team.Draws</td>
                    <td>@team.Losses</td>
                    <td>@team.Points</td>

                </tr>
        }
</table>

src/WinnersLeague.Web/Views/Leaderboards/UsersList.cshtml
@model IEnumerable<UserViewModel>

@{
    ViewData["Title"] = "Users List";
    var counter = 0;
}

<h2>Users Leaderboard</h2>

<table class="table table-hover table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">Full Name</th>
            <th scope="col">Win Stats</th>
            <th scope="col">Points</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            counter++;
            if (this.User.Identity.Name == user.UserName)
            {
                <tr class="bg-warning">
                    <th scope="row">@counter</th>
                    <td>@user.UserName</td>
                    <td>@user.FullName</td>
                    <td>@user.WinStats</td>
                    <td>@user.Points</td>
                </tr>
            }
            else
            {
                <tr class="">
                    <th scope="row">@counter</th>
                    <td>@user.UserName</td>
                    <td>@user.FullName</td>
                    <td>@user.WinStats</td>
                    <td>@user.Points</td>
                </tr>
            }
        }
</table>