src/WinnersLeague.Web/Areas/Admin/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using WinnersLeague.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WinnersLeague.Services.Data.Contracts;
using WinnersLeague.Services.Models;
using WinnersLeague.Web.Areas.Admin.Models;
using AutoMapper;
using WinnersLeague.Common;
using WinnersLeague.Data;

namespace WinnersLeague.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MatchesController : Controller
    {
        private readonly IMatchService matchService;
        private readonly ITeamService teamService;
        private readonly ILeagueService leagueService;
        private readonly IMapper mapper;
        private readonly IRepository<Match> matchRepository;

        public MatchesController(IMatchService matchService,
            ILeagueService leagueService, IRepository<Match> repository,
            ITeamService teamService, IMapper mapper)
        {
            this.matchService = matchService;
            this.teamService = teamService;
            this.leagueService = leagueService;
            this.mapper = mapper;
            this.matchRepository = repository;
        }

        public IActionResult All()
        {
            var matches = this.matchService.GetAll();


            return this.View(matches);
        }

        public IActionResult Create()
        {
            var teamNames = this.teamService.GetAll()
                .Select(x => x.Name)
                .ToList();

            this.ViewData["Teams"] = teamNames;

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MatchInputModel model)
        {
            var league = this.leagueService.GetLeague(model.League);
            var homeTeam = this.teamService.GetTeam(model.HomeTeam);
            var awayTeam = this.teamService.GetTeam(model.AwayTeam);
            var match = mapper.Map<Match>(model);

            match.HomeTeam = homeTeam;
            match.AwayTeam = awayTeam;
            match.League = league;

            await this.matchRepository.AddAsync(match);
            await this.matchRepository.SaveChangesAsync();


            return this.Redirect("/Admin/Matches/All");
        }

        public IActionResult Edit(string id)
        {
            var match = this.matchService
                .GetAll()
                .FirstOrDefault(x => x.Id == id);

            var teamNames = this.teamService.GetAll()
               .Select(x => x.Name)
               .ToList();

            this.ViewData["Teams"] = teamNames;

            return this.View(match);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MatchInputModel model)
        {
            var match = this.matchRepository.All()
                .FirstOrDefault(x => x.Id == model.Id);

            mapper.Map(model, match);

            var league = this.leagueService.GetLeague(model.League);
            var homeTeam = this.teamService.GetTeam(model.HomeTeam);
            var awayTeam = this.teamService.GetTeam(model.AwayTeam);

            match.HomeTeam = homeTeam;
            match.AwayTeam = awayTeam;
            match.League = league;

            await this.matchRepository.SaveChangesAsync();

            return this.RedirectToAction("All", "Matches");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var match = this.matchRepository
                .All()
                .FirstOrDefault(x => x.Id == id);

            this.matchRepository.Delete(match);
            await this.matchRepository.SaveChangesAsync();

            return this.Redirect("/Admin/Matches/All");
        }
    }
}

src/WinnersLeague.Web/Controllers/CommentsController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Common;
    using WinnersLeague.Models;
    using WinnersLeague.Web.Models;

    [Authorize]
    public class CommentsController : Controller
    {
        private readonly IRepository<Comment> commentRepository;
        private readonly IRepository<Match> matchRepository;
        private readonly IRepository<WinnersLeagueUser> userRepository;
        private readonly IMapper mapper;

        public CommentsController(IRepository<Comment> commentRepository,
            IRepository<WinnersLeagueUser> userRepository,
            IMapper mapper,
            IRepository<Match> matchRepository)
        {
            this.commentRepository = commentRepository;
            this.userRepository = userRepository;
            this.mapper = mapper;
            this.matchRepository = matchRepository;
        }

        [HttpPost]
        public async Task<IActionResult> Create(CommentInputModel model)
        {
            var author = this.userRepository
                .All().
                FirstOrDefault(x => x.UserName == this.User.Identity.Name);

            var match = this.matchRepository.All()
                .FirstOrDefault(x => x.Id == model.MatchId);

            var comment = mapper.Map<Comment>(model);

            comment.Author = author;
            match.Comments.Add(comment);

            await this.commentRepository.SaveChangesAsync();


            return this.RedirectToAction("Details", "Matches", match);
        }

        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Delete(string id, string matchId)
        {
            var match = this.matchRepository
                .All()
                .FirstOrDefault(x => x.Id == matchId);

            var comment = this.commentRepository
                .All()
                .FirstOrDefault(x => x.Id == id);

            this.commentRepository.Delete(comment);
            await this.commentRepository.SaveChangesAsync();

            return this.RedirectToAction("Details", "Matches", match);
        }
    }
}

src/WinnersLeague.Web/Controllers/MatchesController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Services.Data.Contracts;

    public class MatchesController : Controller
    {
        private readonly IMatchService matchService;

        public MatchesController(IMatchService matchService)
        {
            this.matchService = matchService;
        }

        [Route("/Matches/All",Name ="AllMatches")]
        public IActionResult All()
        {
            var match = this.matchService
                .GetAll()
                .OrderByDescending(x => x.MatchStart)
                .ToList();
                


            return View(match);
        }

        public IActionResult Details(string id)
        {
            var match = this.matchService
                .GetAll()
                .FirstOrDefault(x => x.Id == id);


            return View(match);
        }
    }
}

src/WinnersLeague.Web/Controllers/TeamsController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Services.Data.Contracts;


    public class TeamsController : Controller
    {
        private readonly ITeamService teamService;

        public TeamsController(ITeamService teamService)
        {
            this.teamService = teamService;
        }

        public IActionResult Details(string id)
        {
            var team = this.teamService
                .GetAll()
                .FirstOrDefault(x => x.Id == id);


            return this.View(team);
        } 

        public IActionResult All(string searchText)
        {
            searchText = searchText ?? "";
            searchText = searchText.Trim();

            var teams = this.teamService.GetAll()
                .Where(x => x.Name.ToLower()
                .Contains(searchText.ToLower()));

            return this.View(teams);
        }
    }
}

src/WinnersLeague.Web/Views/Matches/All.cshtml
@model IEnumerable<MatchViewModel>

@{
    ViewData["Title"] = "All";
}

<h2 class="text-center">All Matches</h2>

@foreach (var match in Model)
{
    <div class="row  d-flex justify-content-center mt-3">
        <div class="card text-center col-lg-8">
            <div class="card-header">
                @match.MatchStart
            </div>
            <div class="card-body  d-flex justify-content-around">
                <div class="col-lg-4">
                    <h4>@match.HomeTeam.Name</h4>
                    <a asp-controller="Teams" asp-action="Details" asp-route-id="@match.HomeTeam.Id">
                        <img src="@Url.Content(match.HomeTeam.Logo)" alt="Home-Team-Picture" width='47' height='47' />
                    </a>
                </div>
                @if (match.Status == MatchStatus.Finished)
                {
                    <div class="col align-self-center">
                        <h1>@match.HomeScore - @match.AwayScore</h1>
                    </div>

                }
                else
                {
                    <div class="col align-self-center">
                        <a asp-controller="Matches" asp-action="Details" asp-route-id="@match.Id">
                            <img src="~/Images/img_418591.png" class="img-responsive" alt="VS" width='74' height='74' />
                        </a>
                    </div>
                }
                <div class="col-lg-4">
                    <h4>@match.AwayTeam.Name</h4>
                    <a asp-controller="Teams" asp-action="Details" asp-route-id="@match.AwayTeam.Id">
                        <img src="@Url.Content(match.AwayTeam.Logo)" alt="Away-Team-Picture" width='47' height='47' />
                    </a>
                </div>
            </div>
        </div>
    </div>
}

src/WinnersLeague.Web/Views/Matches/Details.cshtml
@model MatchViewModel

@{
    ViewData["Title"] = "Match Details";
}

<h2 class="text-center">Match Details</h2>
<div class="row  d-flex justify-content-center">
    <div class="card text-center col-lg-9">
        <div class="card-header">
            @Model.MatchStart
        </div>
        <div class="card-body  d-flex justify-content-around">
            <div class="col-lg-4">
                <h4>@Model.HomeTeam.Name</h4>
                <img src="@Url.Content(Model.HomeTeam.Logo)" alt="Home-Team-Picture" width='94' height='94' />
            </div>
            @if (Model.Status == MatchStatus.Finished)
            {
                <div class="col align-self-center">
                    <h1>@Model.HomeScore - @Model.AwayScore</h1>
                </div>

            }
            else
            {
                <div class="col align-self-center">
                    <img src="~/Images/img_418591.png" class="img-responsive" alt="VS" width='100' height='100' />
                </div>
            }
            <div class="col-lg-4">
                <h4>@Model.AwayTeam.Name</h4>
                <img src="@Url.Content(Model.AwayTeam.Logo)" alt="Away-Team-Picture" width='94' height='94' />
            </div>
        </div>
        <div>
            <h5 class="text-center">Our Suggestion:</h5>
            <h5 class="text-center">@Html.DisplayFor(model => model.OurBetSuggestion)</h5>
        </div>
        <div class="d-flex justify-content-center">
            <hr class="hr-1 w-50 d-flex justify-content-center" />
        </div>

        <div class="card-body  d-flex justify-content-center">
            <div>
                <h2>Description:</h2>
                <h5 class="text-center">@Model.Description</h5>
            </div>
        </div>
    </div>
</div>
<hr class="hr-1 mx-auto w-80" />
@foreach (var comment in Model.Comments)
{
    <div class="col-lg-9 mx-auto">
        <div class="media comment-box">
            <div class="media-left">
                <a href="#">
                    <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading d-flex justify-content-between">
                    @comment.Author
                    @if (this.User.IsInRole("Admin") || comment.Author.UserName == this.User.Identity.Name)
                    {
                        <span><a class="text-dark" asp-controller="Comments" asp-action="Delete" asp-route-matchId="@Model.Id" asp-route-id="@comment.Id"><i class="fas fa-trash-alt"></i></a></span>
                    }
                </h4>
                <p>@comment.Content</p>

            </div>
        </div>
    </div>
}
<hr class=" mx-auto w-80" />
<div class="row mt-5 d-flex justify-content-center">
    @if (this.User.Identity.IsAuthenticated)
    {
        <form class=" col-lg-9" method="post" asp-controller="Comments" asp-action="Create" asp-route-MatchId="@Model.Id">

            <div class="form-group w-50 ">
                <label for="Title">Title</label>
                <input class="form-control" name="Title" placeholder="Title..." />
            </div>

            <div class="form-group w-75">
                <label for="Comment">Comment</label>
                <textarea class="form-control" rows="6" name="Content" placeholder="Write your comment..."></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-default" type="submit">Comment</button>
            </div>
        </form>
    }
    else
    {
        <a asp-area="Identity" asp-page="/Account/Login">You have to Log In to write comments.</a>
    }

</div>