src/WinnersLeague.Web/Areas/Admin/Controllers/BetsController.cs
namespace WinnersLeague.Web.Areas.Admin.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Common;
    using WinnersLeague.Models;

    [Area("Admin")]
    public class BetsController : Controller
    {
        private readonly IRepository<Bet> betRepository;

        public BetsController(IRepository<Bet> betRepository)
        {
            this.betRepository = betRepository;
        }

        public IActionResult All()
        {
            var bets = this.betRepository
                .All()
                .OrderByDescending(x => x.Date)
                .ToList();

            return View(bets);
        }

        public IActionResult Details(string id)
        {
            var bet = this.betRepository
                .All()
                .FirstOrDefault(x => x.Id == id);
                

            return View(bet);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var bets = this.betRepository
                .All()
                .ToList();

            var bet = bets
                .FirstOrDefault(x => x.Id == id);

            this.betRepository.Delete(bet);

            await this.betRepository.SaveChangesAsync();

            return RedirectToAction("All", bets);
        }
    }
}

src/WinnersLeague.Web/Controllers/HomeController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Data;
    using WinnersLeague.Services.Data.Contracts;
    using WinnersLeague.Web.Models;
    using WinnersLeague.Web.Models.HomePageModel;
    using WinnersLeague.Models.Enums;

    public class HomeController : Controller
    {
        private readonly IHomeService homeService;
        private readonly IBetService betService;

        public HomeController(IHomeService homeService, IBetService betService)
        {
            this.homeService = homeService;
            this.betService = betService;
        }

        public IActionResult Index()
        {
            var isAuthenticated = this.User.Identity.IsAuthenticated;

            var homeModel = new HomePageViewModel
            {
                Matches = this.homeService.Matches()
                .Where(x => x.Status != MatchStatus.Finished).ToList()
            };

            if (isAuthenticated)
            {
                var username = this.User.Identity.Name;
                homeModel.MyBet = this.betService.GetCurrentBet(username);
            }
           
            return View(homeModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WinnersLeague.Web/Controllers/MatchesController.cs
namespace WinnersLeague.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using WinnersLeague.Services.Data.Contracts;

    public class MatchesController : Controller
    {
        private readonly IMatchService matchService;

        public MatchesController(IMatchService matchService)
        {
            this.matchService = matchService;
        }

        [Route("/Matches/All",Name ="AllMatches")]
        public IActionResult All()
        {
            var match = this.matchService
                .GetAll()
                .OrderByDescending(x => x.MatchStart)
                .ToList();
                


            return View(match);
        }

        public IActionResult Details(string id)
        {
            var match = this.matchService
                .GetAll()
                .FirstOrDefault(x => x.Id == id);


            return View(match);
        }
    }
}

src/WinnersLeague.Web/Views/Home/Index.cshtml
@model HomePageViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="d-flex justify-content-between">
    <h1>@ViewData["Title"]</h1>
    @if (this.User.Identity.IsAuthenticated)
    {
        <h5>Total Points: @Model.MyBet.User.Points</h5>
    }
    else
    {
            <h5>Please <a asp-area="Identity" asp-page="/Account/Login">Login</a> to bet.</h5>
    }
</div>

<div class="row">
    <div class="col-lg-8">
        <table id="main-grid" class="table table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th class="col-md-6">Matches</th>
                    <th class="col-md-1">1</th>
                    <th class="col-md-1">X</th>
                    <th class="col-md-1">2</th>
                    <th class="col-md-1">U2.5</th>
                    <th class="col-md-1">O2.5</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var match in Model.Matches)
                {
                    if (this.User.Identity.IsAuthenticated)
                    {
                        <tr row_id="@match.Id">
                            <td class="col-md-6"><a class="text-dark" asp-controller="Matches" asp-action="Details" asp-route-id="@match.Id">@match.HomeTeam.Name vs @match.AwayTeam.Name</a></td>
                            <td class="col-md-1"><a asp-controller="Bets" asp-action="AddOdd" asp-route-matchID="@match.Id" asp-route-oddId="@match.Odds.FirstOrDefault(x => x.Type == OddType.HomeWin)?.Id">@match.Odds.FirstOrDefault(x => x.Type == OddType.HomeWin)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-controller="Bets" asp-action="AddOdd" asp-route-matchID="@match.Id" asp-route-oddId="@match.Odds.FirstOrDefault(x => x.Type == OddType.X)?.Id">@match.Odds.FirstOrDefault(x => x.Type == OddType.X)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-controller="Bets" asp-action="AddOdd" asp-route-matchID="@match.Id" asp-route-oddId="@match.Odds.FirstOrDefault(x => x.Type == OddType.AwayWin)?.Id">@match.Odds.FirstOrDefault(x => x.Type == OddType.AwayWin)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-controller="Bets" asp-action="AddOdd" asp-route-matchID="@match.Id" asp-route-oddId="@match.Odds.FirstOrDefault(x => x.Type == OddType.U2_5)?.Id">@match.Odds.FirstOrDefault(x => x.Type == OddType.U2_5)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-controller="Bets" asp-action="AddOdd" asp-route-matchID="@match.Id" asp-route-oddID="@match.Odds.FirstOrDefault(x => x.Type == OddType.O2_5)?.Id">@match.Odds.FirstOrDefault(x => x.Type == OddType.O2_5)?.OddValue</a></td>
                        </tr>
                    }
                    else
                    {
                        <tr row_id="@match.Id">
                            <td class="col-md-6"><a class="text-dark" asp-controller="Matches" asp-action="Details" asp-route-id="@match.Id">@match.HomeTeam.Name vs @match.AwayTeam.Name</a></td>
                            <td class="col-md-1"><a asp-area="Identity" asp-page="/Account/Login">@match.Odds.FirstOrDefault(x => x.Type == OddType.HomeWin)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-area="Identity" asp-page="/Account/Login">@match.Odds.FirstOrDefault(x => x.Type == OddType.X)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-area="Identity" asp-page="/Account/Login">@match.Odds.FirstOrDefault(x => x.Type == OddType.AwayWin)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-area="Identity" asp-page="/Account/Login">@match.Odds.FirstOrDefault(x => x.Type == OddType.U2_5)?.OddValue</a></td>
                            <td class="col-md-1"><a asp-area="Identity" asp-page="/Account/Login">@match.Odds.FirstOrDefault(x => x.Type == OddType.O2_5)?.OddValue</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="col-lg-4">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">My Bet</h5>
                @if (this.User.Identity.IsAuthenticated)
                {
                    @foreach (var odd in Model.MyBet.Odds)
                    {
                        <p>@odd.Match.HomeTeam.Initials vs @odd.Match.AwayTeam.Initials</p>
                        <p>Bet: @Html.DisplayFor(OddType => odd.Type)</p>
                        <div class="d-flex justify-content-between">
                            <p>Odd value: @odd.OddValue</p>
                            <a asp-controller="Bets" asp-action="RemoveOdd" asp-route-oddId="@odd.Id" class="btn btn-secondary btn-sm text-white">Remove</a>
                        </div>
                        <hr />
                    }
                    if (Model.MyBet.Odds.Count > 0)
                    {
                        <form asp-controller="Bets" asp-action="Create" asp-route-Id="@Model.MyBet.Id" method="post">
                            <div class="form-group w-50">
                                <div asp-validation-summary="All" class="text-danger"></div>
                                <input name="BetAmount" max="@Model.MyBet.User.Points" asp-for="MyBet.BetAmount" type="number" step="0.01" class="form-control" />
                                <span asp-validation-for="MyBet.BetAmount" class="text-danger"></span>
                            </div>
                            <div class="d-flex justify-content-around form-group">
                                <div>
                                    <button type="submit" class="btn btn-primary">Bet</button>
                                </div>
                                <div>
                                    <a asp-controller="Bets" asp-action="RemoveAllOdds" class="btn btn-secondary">Cancel</a>
                                </div>
                            </div>
                        </form>
                    }

                }
            </div>
        </div>
    </div>

</div>

@*@section Scripts {
        <script>

            var predicitonList = new Array();
            function submitForm() {
                if (predicitonList.length < 1) {
                    alert('Please select odd')
                } else {
                    $.ajax({
                        url: '/Home/SaveForm',
                        type: 'POST',
                        data: JSON.stringify({ predicitonList }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        processData: true,
                        cache: false,
                        success: function (result) { alert(result); },
                        error: function (e) {
                            console.log(e);
                        }
                    });
                }
            }

            function addToForm(obj) {
                var cardText = $('div.card-body > p.card-text');

                if (predicitonList.length == 0) {
                    cardText.html('');
                }
                predicitonList.push(obj);

                var html = "<div>" + obj.matchName + "&nbsp;" + obj.oddType + "&nbsp;" + obj.odd + "&nbsp;"
                    + "<button onclick = \"removeFromForm(this, '" + obj.match_id + "','" + obj.oddType + "')\">X</button></div><br/>";

                cardText.append(html);
            }

            function changeBackGround(cell) {
                $(cell).attr('style', 'background:red')
            }

            function removeBackGround(match_id, oddType) {
                var rows = $('#main-grid > tbody > tr')
                for (var i = 0; i < rows.length; i++) {
                    if ($(rows[i]).attr("row_id") == match_id) {
                        for (var c = 0; c < rows[i].cells.length; c++) {
                            if ($(rows[i].cells[c]).attr('cell_type') == oddType) {
                                $(rows[i].cells[c]).removeAttr('style')
                            }
                        }
                    }
                }
            }

            function removeFromForm(self, match_id, oddType) {
                for (var i = 0; i < predicitonList.length; i++) {
                    if (predicitonList[i].match_id == match_id && predicitonList[i].oddType == oddType) {
                        predicitonList.pop(predicitonList[i])
                        $(self).parent().remove()
                        removeBackGround(match_id, oddType)
                    }
                }
            }

            $(document).ready(function () {
                $('#main-grid > tbody > tr > td').click(function (event) {
                    var $self = $(this)
                    var match_id = $($self.parent()[0]).attr('row_id');
                    var match = $($self.parent()[0].cells[0]).text();
                    var odd = $self.text();
                    var oddType = $self.attr('cell_type');

                    addToForm({ 'matchName': match, 'match_id': match_id, 'odd': odd, 'oddType': oddType })
                    changeBackGround(this);

                    console.log({ 'matchName': match, 'match_id': match_id, 'odd': odd, 'oddType': oddType });
                })
            })
        </script>
    }*@